"""
Dynamic Agent
A complete agent implementation that uses SystemPromptSkill to manage dynamic personas
"""

from typing import Optional, Dict
from .system_prompt import SystemPromptSkill


class DynamicAgent:
    """
    An AI agent that dynamically changes its role, name, and characteristics
    based on the system prompt generated by SystemPromptSkill
    """
    
    def __init__(self):
        """Initialize the dynamic agent with system prompt skill"""
        self.system_prompt_skill = SystemPromptSkill()
        self.current_system_prompt: Optional[str] = None
        self.conversation_history: list = []
        self.persona_info: Dict[str, str] = {}
    
    def initialize_persona(self) -> str:
        """
        Initialize a new random persona for the agent
        Returns the generated system prompt
        """
        self.current_system_prompt = self.system_prompt_skill.generate_system_prompt()
        self.persona_info = self.system_prompt_skill.get_current_persona()
        self.conversation_history.clear()
        
        return self.current_system_prompt
    
    def initialize_persona_with_profile(self, profile_key: str) -> str:
        """Initialize persona with a specific profile"""
        self.current_system_prompt = self.system_prompt_skill.generate_system_prompt_for_profile(profile_key)
        self.persona_info = self.system_prompt_skill.get_current_persona()
        self.conversation_history.clear()
        
        return self.current_system_prompt
    
    def initialize_persona_with_style(self, style_key: str) -> str:
        """Initialize persona with a specific talking style"""
        self.current_system_prompt = self.system_prompt_skill.generate_system_prompt_for_style(style_key)
        self.persona_info = self.system_prompt_skill.get_current_persona()
        self.conversation_history.clear()
        
        return self.current_system_prompt
    
    def initialize_persona_custom(self, profile_key: str, style_key: str) -> str:
        """Initialize persona with specific profile and style"""
        self.current_system_prompt = self.system_prompt_skill.generate_system_prompt_custom(profile_key, style_key)
        self.persona_info = self.system_prompt_skill.get_current_persona()
        self.conversation_history.clear()
        
        return self.current_system_prompt
    
    def change_persona(self) -> str:
        """
        Change to a new random persona
        Useful for switching character mid-conversation
        """
        return self.initialize_persona()
    
    def get_current_persona(self) -> Dict[str, str]:
        """Get information about the current persona"""
        return self.persona_info
    
    def get_system_prompt(self) -> Optional[str]:
        """Get the current system prompt"""
        return self.current_system_prompt
    
    def add_to_history(self, role: str, message: str) -> None:
        """
        Add a message to conversation history
        Args:
            role: 'user' or 'assistant'
            message: The message content
        """
        self.conversation_history.append({
            'role': role,
            'content': message
        })
    
    def get_conversation_history(self) -> list:
        """Get the entire conversation history"""
        return self.conversation_history
    
    def clear_history(self) -> None:
        """Clear conversation history"""
        self.conversation_history.clear()
    
    def get_agent_info(self) -> Dict:
        """Get complete agent information"""
        return {
            'persona': self.persona_info,
            'system_prompt': self.current_system_prompt,
            'history_length': len(self.conversation_history),
            'available_profiles': self.system_prompt_skill.list_available_profiles(),
            'available_styles': self.system_prompt_skill.list_available_styles()
        }
